services:
  crowallet-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: crowallet-backend:0.2.0
    ports:
      - "0.0.0.0:8082:8082"
    volumes:
      - ./backend/data:/app/data
    container_name: crowallet-backend-container
    restart: unless-stopped

  crowallet-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: crowallet-frontend:0.2.0
    ports:
      - "0.0.0.0:3000:3000"
    container_name: crowallet-frontend-container
    depends_on:
      - crowallet-backend
    restart: unless-stopped

  sqlite-web:
    image: ghcr.io/coleifer/sqlite-web:latest
    ports:
      - "0.0.0.0:8083:8080"
    volumes:
      - ./backend/data:/data
    environment:
      - SQLITE_DATABASE=wallet.db
    stdin_open: true
    tty: true
    restart: unless-stopped