spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: admin
    password: admin 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

